var parasha4719 =[
    "Parashá 47",
    "dia 19",
    "Deuteronômio 14",
    "¹ Filhos sois do Senhor vosso Deus; não vos dareis golpes, nem fareis calva entre vossos olhos por causa de algum morto. ",
    "² Porque és povo santo ao Senhor teu Deus; e o Senhor te escolheu, de todos os povos que há sobre a face da terra, para lhe seres o seu próprio povo. ",
    "³ Nenhuma coisa abominável comereis. ",
    "⁴ Estes são os animais que comereis: o boi, a ovelha, e a cabra. ",
    "⁵ O veado e a corça, e o búfalo, e a cabra montês, e o texugo, e a camurça, e o gamo. ",
    "⁶ Todo o animal que tem unhas fendidas, divididas em duas, que rumina, entre os animais, aquilo comereis. ",
    "⁷ Porém estes não comereis, dos que somente ruminam, ou que tem a unha fendida: o camelo, e a lebre, e o coelho, porque ruminam mas não têm a unha fendida; imundos vos serão. ",
    "⁸ Nem o porco, porque tem unha fendida, mas não rumina; imundo vos será; não comereis da carne destes, e não tocareis nos seus cadáveres. ",
    "⁹ Isto comereis de tudo o que há nas águas; tudo o que tem barbatanas e escamas comereis. ",
    "¹⁰ Mas tudo o que não tiver barbatanas nem escamas não o comereis; imundo vos será. ",
    "¹¹ Toda a ave limpa comereis. ",
    "¹² Porém estas são as que não comereis: a águia, e o quebrantosso, e o xofrango, ",
    "¹³ E o abutre, e o falcão, e o milhafre, segundo a sua espécie. ",
    "¹⁴ E todo o corvo, segundo a sua espécie. ",
    "¹⁵ E o avestruz, e o mocho, e a gaivota, e o gavião, segundo a sua espécie. ",
    "¹⁶ E o bufo, e a coruja, e a gralha, ",
    "¹⁷ E o cisne, e o pelicano, e o corvo marinho, ",
    "¹⁸ E a cegonha, e a garça, segundo a sua espécie, e a poupa, e o morcego. ",
    "¹⁹ Também todo o inseto que voa, vos será imundo; não se comerá. ",
    "²⁰ Toda a ave limpa comereis. ",
    "²¹ Não comereis nenhum animal morto; ao estrangeiro, que está dentro das tuas portas, o darás a comer, ou o venderás ao estranho, porquanto és povo santo ao Senhor teu Deus. Não cozerás o cabrito com leite da sua mãe. ",
    "²² Certamente darás os dízimos de todo o fruto da tua semente, que cada ano se recolher do campo. ",
    "²³ E, perante o Senhor teu Deus, no lugar que escolher para ali fazer habitar o seu nome, comerás os dízimos do teu grão, do teu mosto e do teu azeite, e os primogênitos das tuas vacas e das tuas ovelhas; para que aprendas a temer ao Senhor teu Deus todos os dias. ",
    "²⁴ E quando o caminho te for tão comprido que os não possas levar, por estar longe de ti o lugar que escolher o Senhor teu Deus para ali pôr o seu nome, quando o Senhor teu Deus te tiver abençoado; ",
    "²⁵ Então vende-os, e ata o dinheiro na tua mão, e vai ao lugar que escolher o Senhor teu Deus; ",
    "²⁶ E aquele dinheiro darás por tudo o que deseja a tua alma, por vacas, e por ovelhas, e por vinho, e por bebida forte, e por tudo o que te pedir a tua alma; come-o ali perante o Senhor teu Deus, e alegra-te, tu e a tua casa; ",
    "²⁷ Porém não desampararás o levita que está dentro das tuas portas; pois não tem parte nem herança contigo. ",
    "²⁸ Ao fim de três anos tirarás todos os dízimos da tua colheita no mesmo ano, e os recolherás dentro das tuas portas; ",
    "²⁹ Então virá o levita (pois nem parte nem herança tem contigo), e o estrangeiro, e o órfão, e a viúva, que estão dentro das tuas portas, e comerão, e fartar-se-ão; para que o Senhor teu Deus te abençoe em toda a obra que as tuas mãos fizerem. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

]

var parasha4720=[
    "Parashá 47",
    "dia 20",
    "Deuteronômio 15",
    "¹ Ao fim dos sete anos farás remissão. ",
    "² Este, pois, é o modo da remissão: todo o credor remitirá o que emprestou ao seu próximo; não o exigirá do seu próximo ou do seu irmão, pois a remissão do Senhor é apregoada. ",
    "³ Do estrangeiro o exigirás; mas o que tiveres em poder de teu irmão a tua mão o remitirá. ",
    "⁴ Exceto quando não houver entre ti pobre algum; pois o Senhor abundantemente te abençoará na terra que o Senhor teu Deus te dará por herança, para possuí-la. ",
    "⁵ Se somente ouvires diligentemente a voz do Senhor teu Deus para cuidares em cumprir todos estes mandamentos que hoje te ordeno; ",
    "⁶ Porque o Senhor teu Deus te abençoará, como te tem falado; assim, emprestarás a muitas nações, mas não tomarás empréstimos; e dominarás sobre muitas nações, mas elas não dominarão sobre ti. ",
    "⁷ Quando entre ti houver algum pobre, de teus irmãos, em alguma das tuas portas, na terra que o Senhor teu Deus te dá, não endurecerás o teu coração, nem fecharás a tua mão a teu irmão que for pobre; ",
    "⁸ Antes lhe abrirás de todo a tua mão, e livremente lhe emprestarás o que lhe falta, quanto baste para a sua necessidade. ",
    "⁹ Guarda-te, que não haja palavra perversa no teu coração, dizendo: Vai-se aproximando o sétimo ano, o ano da remissão; e que o teu olho seja maligno para com teu irmão pobre, e não lhe dês nada; e que ele clame contra ti ao Senhor, e que haja em ti pecado. ",
    "¹⁰ Livremente lhe darás, e que o teu coração não seja maligno, quando lhe deres; pois por esta causa te abençoará o Senhor teu Deus em toda a tua obra, e em tudo o que puseres a tua mão. ",
    "¹¹ Pois nunca deixará de haver pobre na terra; pelo que te ordeno, dizendo: Livremente abrirás a tua mão para o teu irmão, para o teu necessitado, e para o teu pobre na tua terra. ",
    "¹² Quando teu irmão hebreu ou irmã hebreia se vender a ti, seis anos te servirá, mas no sétimo ano o deixarás ir livre. ",
    "¹³ E, quando o deixares ir livre, não o despedirás vazio. ",
    "¹⁴ Liberalmente o fornecerás do teu rebanho, e da tua eira, e do teu lagar; daquilo com que o Senhor teu Deus te tiver abençoado lhe darás. ",
    "¹⁵ E lembrar-te-ás de que foste servo na terra do Egito, e de que o Senhor teu Deus te resgatou; portanto hoje te ordeno isso. ",
    "¹⁶ Porém se ele te disser: Não sairei de ti; porquanto te amo a ti, e a tua casa, por estar bem contigo; ",
    "¹⁷ Então tomarás uma sovela, e lhe furarás a orelha à porta, e teu servo será para sempre; e também assim farás à tua serva. ",
    "¹⁸ Não seja duro aos teus olhos, quando despedi-lo liberto de ti; pois seis anos te serviu em equivalência ao dobro do salário do diarista; assim o Senhor teu Deus te abençoará em tudo o que fizeres. ",
    "¹⁹ Todo o primogênito que nascer das tuas vacas e das tuas ovelhas, o macho santificarás ao Senhor teu Deus; com o primogênito do teu boi não trabalharás, nem tosquiarás o primogênito das tuas ovelhas. ",
    "²⁰ Perante o Senhor teu Deus os comerás de ano em ano, no lugar que o Senhor escolher, tu e a tua casa. ",
    "²¹ Porém, havendo nele algum defeito, se for coxo, ou cego, ou tiver qualquer defeito, não o sacrificarás ao Senhor teu Deus. ",
    "²² Nas tuas portas o comerás; o imundo e o limpo o comerão também, como da corça ou do veado. ",
    "²³ Somente o seu sangue não comerás; sobre a terra o derramarás como água. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

]
var parasha4721 =[
    "Parashá 47",
    "dia 21",
    "Deuteronômio 16 v 1 ate 17",
    "¹ Guarda o mês de Abibe, e celebra a páscoa ao Senhor teu Deus; porque no mês de Abibe o Senhor teu Deus te tirou do Egito, de noite. ",
    "² Então sacrificarás a páscoa ao Senhor teu Deus, das ovelhas e das vacas, no lugar que o Senhor escolher para ali fazer habitar o seu nome. ",
    "³ Nela não comerás levedado; sete dias nela comerás pães ázimos, pão de aflição (porquanto apressadamente saíste da terra do Egito), para que te lembres do dia da tua saída da terra do Egito, todos os dias da tua vida. ",
    "⁴ Levedado não aparecerá contigo por sete dias em todos os teus termos; também da carne que matares à tarde, no primeiro dia, nada ficará até à manhã. ",
    "⁵ Não poderás sacrificar a páscoa em nenhuma das tuas portas que te dá o Senhor teu Deus; ",
    "⁶ Senão no lugar que escolher o Senhor teu Deus, para fazer habitar o seu nome, ali sacrificarás a páscoa à tarde, ao pôr do sol, ao tempo determinado da tua saída do Egito. ",
    "⁷ Então a cozerás, e comerás no lugar que escolher o Senhor teu Deus; depois voltarás pela manhã, e irás às tuas tendas. ",
    "⁸ Seis dias comerás pães ázimos e no sétimo dia é solenidade ao Senhor teu Deus; nenhum trabalho farás. ",
    "⁹ Sete semanas contarás; desde que a foice começar na seara iniciarás a contar as sete semanas. ",
    "¹⁰ Depois celebrarás a festa das semanas ao Senhor teu Deus; o que deres será oferta voluntária da tua mão, segundo o Senhor teu Deus te houver abençoado. ",
    "¹¹ E te alegrarás perante o Senhor teu Deus, tu, e teu filho, e tua filha, e o teu servo, e a tua serva, e o levita que está dentro das tuas portas, e o estrangeiro, e o órfão, e a viúva, que estão no meio de ti, no lugar que o Senhor teu Deus escolher para ali fazer habitar o seu nome. ",
    "¹² E lembrar-te-ás de que foste servo no Egito; e guardarás estes estatutos, e os cumprirás. ",
    "¹³ A festa dos tabernáculos celebrarás sete dias, quando tiveres colhido da tua eira e do teu lagar. ",
    "¹⁴ E, na tua festa, alegrar-te-ás, tu, e teu filho, e tua filha, e o teu servo, e a tua serva, e o levita, e o estrangeiro, e o órfão, e a viúva, que estão dentro das tuas portas. ",
    "¹⁵ Sete dias celebrarás a festa ao Senhor teu Deus, no lugar que o Senhor escolher; porque o Senhor teu Deus te há de abençoar em toda a tua colheita, e em todo o trabalho das tuas mãos; por isso certamente te alegrarás. ",
    "¹⁶ Três vezes no ano todo o homem entre ti aparecerá perante o Senhor teu Deus, no lugar que escolher, na festa dos pães ázimos, e na festa das semanas, e na festa dos tabernáculos; porém não aparecerá vazio perante o Senhor; ",
    "¹⁷ Cada um, conforme ao dom da sua mão, conforme a bênção do Senhor teu Deus, que lhe tiver dado. ",
    "************************************************************************************",
    "HAFTARÁ RE´EH",
    "iSAÍAS 54 v 11 ",
    "Isaías 54:11 Tu, oprimida, arrojada com a tormenta e desconsolada, eis que eu assentarei as tuas pedras com todo o ornamento, e te fundarei sobre as safiras. ",
    "************************************************************************************",
    "ISAÍAS 55 v 5",
    "Isaías 55:5 Eis que chamarás a uma nação que não conheces, e uma nação que nunca te conheceu correrá para ti, por amor do Senhor teu Deus, e do Santo de Israel; porque ele te glorificou. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",   
]
var parasha4722=[
    "Parashá 47",
    "dia 22",
    "ESCRITOS NAZARENOS",
    " 1º CORINTIOS 5 V 9 AO 13",
    "9 Já por carta vos tenho escrito, que não vos associeis com os fornicadores;",
    "¹⁰ Ainda que não inteiramente com os fornicadores deste mundo, ou com os avarentos, ou com os roubadores, ou com os idólatras; porque então vos seria necessário sair do mundo. ",
    "¹¹ Mas agora vos escrevi que não vos associeis com aquele que, dizendo-se irmão, for fornicador, ou avarento, ou idólatra, ou maldizente, ou beberrão, ou roubador; com o tal nem ainda comais. ",
    "¹² Porque, que tenho eu em julgar também os que estão de fora? Não julgais vós os que estão dentro? ",
    "¹³ Mas Deus julga os que estão de fora. Tirai, pois, dentre vós a esse iníquo. ",
    "*****************************************************************",
    " 1º JOÃO 4 V 1 AO 6",
    "¹ Amados, não creiais a todo o espírito, mas provai se os espíritos são de Deus, porque já muitos falsos profetas se têm levantado no mundo. ",
    "² Nisto conhecereis o Espírito de Deus: Todo o espírito que confessa que Jesus Cristo veio em carne é de Deus; ",
    "³ E todo o espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito do anticristo, do qual já ouvistes que há de vir, e eis que já agora está no mundo. ",
    "⁴ Filhinhos, sois de Deus, e já os tendes vencido; porque maior é o que está em vós do que o que está no mundo. ",
    "⁵ Do mundo são, por isso falam do mundo, e o mundo os ouve. ",
    "⁶ Nós somos de Deus; aquele que conhece a Deus ouve-nos; aquele que não é de Deus não nos ouve. Nisto conhecemos nós o espírito da verdade e o espírito do erro. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

    
    
]



var parasha4723 =[
    "Parashá 47",
    "dia 23",
    "Shabbat Shalom á todos",
    "Hoje as 13:00 hrs ",
    "Reunião na congregação",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63

]



var data = new Date()
var dia = data.getDate()
var hora = data.getHours
var parasha = ""



 if (dia==20) {
    

    parasha=parasha4720 
 }
 if (dia==19) {
    
      parasha=parasha4719  
    
     
 }
 if (dia==21) {
    
    parasha=parasha4721  
  
   
}
if (dia==22) {
    
    parasha=parasha4722  
  
   
}
if (dia==23) {
    
    parasha=parasha4723  
  
   
}






export {parasha}



