var parasha4719 =[
    "Parashá 47",
    "dia 19",
    "Deuteronômio 14",
    "¹ Filhos sois do Senhor vosso Deus; não vos dareis golpes, nem fareis calva entre vossos olhos por causa de algum morto. ",
    "² Porque és povo santo ao Senhor teu Deus; e o Senhor te escolheu, de todos os povos que há sobre a face da terra, para lhe seres o seu próprio povo. ",
    "³ Nenhuma coisa abominável comereis. ",
    "⁴ Estes são os animais que comereis: o boi, a ovelha, e a cabra. ",
    "⁵ O veado e a corça, e o búfalo, e a cabra montês, e o texugo, e a camurça, e o gamo. ",
    "⁶ Todo o animal que tem unhas fendidas, divididas em duas, que rumina, entre os animais, aquilo comereis. ",
    "⁷ Porém estes não comereis, dos que somente ruminam, ou que tem a unha fendida: o camelo, e a lebre, e o coelho, porque ruminam mas não têm a unha fendida; imundos vos serão. ",
    "⁸ Nem o porco, porque tem unha fendida, mas não rumina; imundo vos será; não comereis da carne destes, e não tocareis nos seus cadáveres. ",
    "⁹ Isto comereis de tudo o que há nas águas; tudo o que tem barbatanas e escamas comereis. ",
    "¹⁰ Mas tudo o que não tiver barbatanas nem escamas não o comereis; imundo vos será. ",
    "¹¹ Toda a ave limpa comereis. ",
    "¹² Porém estas são as que não comereis: a águia, e o quebrantosso, e o xofrango, ",
    "¹³ E o abutre, e o falcão, e o milhafre, segundo a sua espécie. ",
    "¹⁴ E todo o corvo, segundo a sua espécie. ",
    "¹⁵ E o avestruz, e o mocho, e a gaivota, e o gavião, segundo a sua espécie. ",
    "¹⁶ E o bufo, e a coruja, e a gralha, ",
    "¹⁷ E o cisne, e o pelicano, e o corvo marinho, ",
    "¹⁸ E a cegonha, e a garça, segundo a sua espécie, e a poupa, e o morcego. ",
    "¹⁹ Também todo o inseto que voa, vos será imundo; não se comerá. ",
    "²⁰ Toda a ave limpa comereis. ",
    "²¹ Não comereis nenhum animal morto; ao estrangeiro, que está dentro das tuas portas, o darás a comer, ou o venderás ao estranho, porquanto és povo santo ao Senhor teu Deus. Não cozerás o cabrito com leite da sua mãe. ",
    "²² Certamente darás os dízimos de todo o fruto da tua semente, que cada ano se recolher do campo. ",
    "²³ E, perante o Senhor teu Deus, no lugar que escolher para ali fazer habitar o seu nome, comerás os dízimos do teu grão, do teu mosto e do teu azeite, e os primogênitos das tuas vacas e das tuas ovelhas; para que aprendas a temer ao Senhor teu Deus todos os dias. ",
    "²⁴ E quando o caminho te for tão comprido que os não possas levar, por estar longe de ti o lugar que escolher o Senhor teu Deus para ali pôr o seu nome, quando o Senhor teu Deus te tiver abençoado; ",
    "²⁵ Então vende-os, e ata o dinheiro na tua mão, e vai ao lugar que escolher o Senhor teu Deus; ",
    "²⁶ E aquele dinheiro darás por tudo o que deseja a tua alma, por vacas, e por ovelhas, e por vinho, e por bebida forte, e por tudo o que te pedir a tua alma; come-o ali perante o Senhor teu Deus, e alegra-te, tu e a tua casa; ",
    "²⁷ Porém não desampararás o levita que está dentro das tuas portas; pois não tem parte nem herança contigo. ",
    "²⁸ Ao fim de três anos tirarás todos os dízimos da tua colheita no mesmo ano, e os recolherás dentro das tuas portas; ",
    "²⁹ Então virá o levita (pois nem parte nem herança tem contigo), e o estrangeiro, e o órfão, e a viúva, que estão dentro das tuas portas, e comerão, e fartar-se-ão; para que o Senhor teu Deus te abençoe em toda a obra que as tuas mãos fizerem. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

]

var parasha4718p=[
    "Parashá 47",
    "dia 18 tarde",
    "Deuteronômio 13",
    "¹ Quando profeta ou sonhador de sonhos se levantar no meio de ti, e te der um sinal ou prodígio,  ",
    "² E suceder o tal sinal ou prodígio, de que te houver falado, dizendo: Vamos após outros deuses, que não conheceste, e sirvamo-los; ",
    "³ Não ouvirás as palavras daquele profeta ou sonhador de sonhos; porquanto o Senhor vosso Deus vos prova, para saber se amais o Senhor vosso Deus com todo o vosso coração, e com toda a vossa alma. ",
    "⁴ Após o Senhor vosso Deus andareis, e a ele temereis, e os seus mandamentos guardareis, e a sua voz ouvireis, e a ele servireis, e a ele vos achegareis. ",
    "⁵ E aquele profeta ou sonhador de sonhos morrerá, pois falou rebeldia contra o Senhor vosso Deus, que vos tirou da terra do Egito, e vos resgatou da casa da servidão, para te apartar do caminho que te ordenou o Senhor teu Deus, para andares nele: assim tirarás o mal do meio de ti. ",
    "⁶ Quando te incitar teu irmão, filho da tua mãe, ou teu filho, ou tua filha, ou a mulher do teu seio, ou teu amigo, que te é como a tua alma, dizendo-te em segredo: Vamos, e sirvamos a outros deuses que não conheceste, nem tu nem teus pais; ",
    "⁷ Dentre os deuses dos povos que estão em redor de vós, perto ou longe de ti, desde uma extremidade da terra até à outra extremidade; ",
    "⁸ Não consentirás com ele, nem o ouvirás; nem o teu olho o poupará, nem terás piedade dele, nem o esconderás; ",
    "⁹ Mas certamente o matarás; a tua mão será a primeira contra ele, para o matar; e depois a mão de todo o povo. ",
    "¹⁰ E o apedrejarás, até que morra, pois te procurou apartar do Senhor teu Deus, que te tirou da terra do Egito, da casa da servidão; ",
    "¹¹ Para que todo o Israel o ouça e o tema, e não torne a fazer semelhante maldade no meio de ti. ",
    "¹² Quando ouvires dizer, de alguma das tuas cidades que o Senhor teu Deus te dá para ali habitar: ",
    "¹³ Uns homens, filhos de Belial, que saíram do meio de ti, incitaram os moradores da sua cidade, dizendo: Vamos, e sirvamos a outros deuses que não conhecestes; ",
    "¹⁴ Então inquirirás e investigarás, e com diligência perguntarás; e eis que, sendo verdade, e certo que se fez tal abominação no meio de ti; ",
    "¹⁵ Certamente ferirás, ao fio da espada, os moradores daquela cidade, destruindo a ela e a tudo o que nela houver, até os animais. ",
    "¹⁶ E ajuntarás todo o seu despojo no meio da sua praça; e a cidade e todo o seu despojo queimarás totalmente para o Senhor teu Deus, e será montão perpétuo, nunca mais se edificará. ",
    "¹⁷ Também não se pegará à tua mão nada do anátema, para que o Senhor se aparte do ardor da sua ira, e te faça misericórdia, e tenha piedade de ti, e te multiplique, como jurou a teus pais; ",
    "¹⁸ Quando ouvires a voz do Senhor teu Deus, para guardares todos os seus mandamentos que hoje te ordeno; para fazeres o que for reto aos olhos do Senhor teu Deus. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

]


var parasha4718m=[
    "Parashá 47",
    "dia 18 manhã",
    "Deuteronômio 12",
    "¹ Estes são os estatutos e os juízos que tereis cuidado em cumprir na terra que vos deu o Senhor Deus de vossos pais, para a possuir todos os dias que viverdes sobre a terra. ",
    "² Totalmente destruireis todos os lugares, onde as nações que possuireis serviram os seus deuses, sobre as altas montanhas, e sobre os outeiros, e debaixo de toda a árvore frondosa; ",
    "³ E derrubareis os seus altares, e quebrareis as suas estátuas, e os seus bosques queimareis a fogo, e destruireis as imagens esculpidas dos seus deuses, e apagareis o seu nome daquele lugar. ",
    "⁴ Assim não fareis ao Senhor vosso Deus; ",
    "⁵ Mas o lugar que o Senhor vosso Deus escolher de todas as vossas tribos, para ali pôr o seu nome, buscareis, para sua habitação, e ali vireis. ",
    "⁶ E ali trareis os vossos holocaustos, e os vossos sacrifícios, e os vossos dízimos, e a oferta alçada da vossa mão, e os vossos votos, e as vossas ofertas voluntárias, e os primogênitos das vossas vacas e das vossas ovelhas. ",
    "⁷ E ali comereis perante o Senhor vosso Deus, e vos alegrareis em tudo em que puserdes a vossa mão, vós e as vossas casas, no que abençoar o Senhor vosso Deus. ",
    "⁸ Não fareis conforme a tudo o que hoje fazemos aqui, cada qual tudo o que bem parece aos seus olhos. ",
    "⁹ Porque até agora não entrastes no descanso e na herança que vos dá o Senhor vosso Deus. ",
    "¹⁰ Mas passareis o Jordão, e habitareis na terra que vos fará herdar o Senhor vosso Deus; e vos dará repouso de todos os vossos inimigos em redor, e morareis seguros. ",
    "¹¹ Então haverá um lugar que escolherá o Senhor vosso Deus para ali fazer habitar o seu nome; ali trareis tudo o que vos ordeno; os vossos holocaustos, e os vossos sacrifícios, e os vossos dízimos, e a oferta alçada da vossa mão, e toda a escolha dos vossos votos que fizerdes ao Senhor.",
    "¹² E vos alegrareis perante o Senhor vosso Deus, vós, e vossos filhos, e vossas filhas, e os vossos servos, e as vossas servas, e o levita que está dentro das vossas portas; pois convosco não tem parte nem herança. ",
    "¹³ Guarda-te, que não ofereças os teus holocaustos em todo o lugar que vires; ",
    "¹⁴ Mas no lugar que o Senhor escolher numa das tuas tribos ali oferecerás os teus holocaustos, e ali farás tudo o que te ordeno. ",
    "¹⁵ Porém, conforme a todo o desejo da tua alma, matarás e comerás carne, dentro das tuas portas, segundo a bênção do Senhor teu Deus, que te dá em todas as tuas portas; o imundo e o limpo dela comerá, como do corço e do veado; ",
    "¹⁶ Tão somente o sangue não comereis; sobre a terra o derramareis como água. ",
    "¹⁷ Dentro das tuas portas não poderás comer o dízimo do teu grão, nem do teu mosto, nem do teu azeite, nem os primogênitos das tuas vacas, nem das tuas ovelhas; nem nenhum dos teus votos, que houveres prometido, nem as tuas ofertas voluntárias, nem a oferta alçada da tua mão.",
    "¹⁸ Mas os comerás perante o Senhor teu Deus, no lugar que escolher o Senhor teu Deus, tu, e teu filho, e a tua filha, e o teu servo, e a tua serva, e o levita que está dentro das tuas portas; e perante o Senhor teu Deus te alegrarás em tudo em que puseres a tua mão. ",
    "¹⁹ Guarda-te, que não desampares ao levita todos os teus dias na terra. ",
    "²⁰ Quando o Senhor teu Deus dilatar os teus termos, como te disse, e disseres: Comerei carne; porquanto a tua alma tem desejo de comer carne; conforme a todo o desejo da tua alma, comerás carne. ",
    "²¹ Se estiver longe de ti o lugar que o Senhor teu Deus escolher, para ali pôr o seu nome, então matarás das tuas vacas e das tuas ovelhas, que o Senhor te tiver dado, como te tenho ordenado; e comerás dentro das tuas portas, conforme a todo o desejo da tua alma. ",
    "²² Porém, como se come o corço e o veado, assim comerás; o imundo e o limpo também comerão deles. ",
    "²³ Somente esforça-te para que não comas o sangue; pois o sangue é vida; pelo que não comerás a vida com a carne; ",
    "²⁴ Não o comerás; na terra o derramarás como água. ",
    "²⁵ Não o comerás; para que bem te suceda a ti, e a teus filhos, depois de ti, quando fizeres o que for reto aos olhos do Senhor. ",
    "²⁶ Porém, as coisas santas que tiveres, e os teus votos tomarás, e virás ao lugar que o Senhor escolher. ",
    "²⁷ E oferecerás os teus holocaustos, a carne e o sangue sobre o altar do Senhor teu Deus; e o sangue dos teus sacrifícios se derramará sobre o altar do Senhor teu Deus; porém a carne comerás. ",
    "²⁸ Guarda e ouve todas estas palavras que te ordeno, para que bem te suceda a ti e a teus filhos depois de ti para sempre, quando fizeres o que for bom e reto aos olhos do Senhor teu Deus. ",
    "²⁹ Quando o Senhor teu Deus desarraigar de diante de ti as nações, aonde vais a possuí-las, e as possuíres e habitares na sua terra, ",
    "³⁰ Guarda-te, que não te enlaces seguindo-as, depois que forem destruídas diante de ti; e que não perguntes acerca dos seus deuses, dizendo: Assim como serviram estas nações os seus deuses, do mesmo modo também farei eu. ",
    "³¹ Assim não farás ao Senhor teu Deus; porque tudo o que é abominável ao Senhor, e que ele odeia, fizeram eles a seus deuses; pois até seus filhos e suas filhas queimaram no fogo aos seus deuses. ",
    "³² Tudo o que eu te ordeno, observarás para fazer; nada lhe acrescentarás nem diminuirás. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

]


var parasha4717 =[
    "Parashá 47",
    "dia 17",
    "Deuteronômio 11",
    "¹ Amarás, pois, ao Senhor teu Deus, e guardarás as suas ordenanças, e os seus estatutos, e os seus juízos, e os seus mandamentos, todos os dias. ",
    "² E hoje sabereis que falo, não com vossos filhos, que o não sabem, e não viram a instrução do Senhor vosso Deus, a sua grandeza, a sua mão forte, e o seu braço estendido; ",
    "³ Nem tampouco os seus sinais, nem os seus feitos, que fez no meio do Egito a Faraó, rei do Egito, e a toda a sua terra; ",
    "⁴ Nem o que fez ao exército dos egípcios, aos seus cavalos e aos seus carros, fazendo passar sobre eles as águas do Mar Vermelho quando vos perseguiam, e como o Senhor os destruiu, até ao dia de hoje; ",
    "⁵ Nem o que vos fez no deserto, até que chegastes a este lugar; ",
    "⁶ E o que fez a Datã e a Abirão, filhos de Eliabe, filho de Rúben; como a terra abriu a sua boca e os tragou com as suas casas e com as suas tendas, como também tudo o que subsistia, e lhes pertencia, no meio de todo o Israel; ",
    "⁷ Porquanto os vossos olhos são os que viram toda a grande obra que fez o Senhor. ",
    "⁸ Guardai, pois, todos os mandamentos que eu vos ordeno hoje, para que sejais fortes, e entreis, e ocupeis a terra que passais a possuir; ",
    "⁹ E para que prolongueis os dias na terra que o Senhor jurou dar a vossos pais e à sua descendência, terra que mana leite e mel. ",
    "¹⁰ Porque a terra que passas a possuir não é como a terra do Egito, de onde saíste, em que semeavas a tua semente, e a regavas com o teu pé, como a uma horta. ",
    "¹¹ Mas a terra que passais a possuir é terra de montes e de vales; da chuva dos céus beberá as águas; ",
    "¹² Terra de que o Senhor teu Deus tem cuidado; os olhos do Senhor teu Deus estão sobre ela continuamente, desde o princípio até ao fim do ano. ",
    "¹³ E será que, se diligentemente obedecerdes a meus mandamentos que hoje vos ordeno, de amar ao Senhor vosso Deus, e de o servir de todo o vosso coração e de toda a vossa alma,",
    "¹⁴ Então darei a chuva da vossa terra a seu tempo, a temporã e a serôdia, para que recolhais o vosso grão, e o vosso mosto e o vosso azeite. ",
    "¹⁵ E darei erva no teu campo aos teus animais, e comerás, e fartar-te-ás. ",
    "¹⁶ Guardai-vos, que o vosso coração não se engane, e vos desvieis, e sirvais a outros deuses, e vos inclineis perante eles; ",
    "¹⁷ E a ira do Senhor se acenda contra vós, e feche ele os céus, e não haja água, e a terra não dê o seu fruto, e cedo pereçais da boa terra que o Senhor vos dá. ",
    "¹⁸ Ponde, pois, estas minhas palavras no vosso coração e na vossa alma, e atai-as por sinal na vossa mão, para que estejam por frontais entre os vossos olhos. ",
    "¹⁹ E ensinai-as a vossos filhos, falando delas assentado em tua casa, e andando pelo caminho, e deitando-te, e levantando-te;",
    "²⁰ E escreve-as nos umbrais de tua casa, e nas tuas portas; ",
    "²¹ Para que se multipliquem os vossos dias e os dias de vossos filhos na terra que o Senhor jurou a vossos pais dar-lhes, como os dias dos céus sobre a terra.",
    "²² Porque se diligentemente guardardes todos estes mandamentos, que vos ordeno para os guardardes, amando ao Senhor vosso Deus, andando em todos os seus caminhos, e a ele vos achegardes, ",
    "²³ Também o Senhor, de diante de vós, lançará fora todas estas nações, e possuireis nações maiores e mais poderosas do que vós. ",
    "²⁴ Todo o lugar que pisar a planta do vosso pé será vosso; desde o deserto, e desde o Líbano, desde o rio, o rio Eufrates, até ao mar ocidental, será o vosso termo. ",
    "²⁵ Ninguém resistirá diante de vós; o Senhor vosso Deus porá sobre toda a terra, que pisardes, o vosso terror e o temor de vós, como já vos tem dito. ",
    "²⁶ Eis que hoje eu ponho diante de vós a bênção e a maldição; ",
    "²⁷ A bênção, quando cumprirdes os mandamentos do Senhor vosso Deus, que hoje vos mando; ",
    "²⁸ Porém a maldição, se não cumprirdes os mandamentos do Senhor vosso Deus, e vos desviardes do caminho que hoje vos ordeno, para seguirdes outros deuses que não conhecestes. ",
    "²⁹ E será que, quando o Senhor teu Deus te introduzir na terra, a que vais para possuí-la, então pronunciarás a bênção sobre o monte Gerizim, e a maldição sobre o monte Ebal. ",
    "³⁰ Porventura não estão eles além do Jordão, junto ao caminho do pôr do sol, na terra dos cananeus, que habitam na campina defronte de Gilgal, junto aos carvalhais de Moré? ",
    "³¹ Porque passareis o Jordão para entrardes a possuir a terra, que vos dá o Senhor vosso Deus; e a possuireis, e nela habitareis. ",
    "³² Tende, pois, cuidado em cumprir todos os estatutos e os juízos, que eu hoje vos proponho. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63

]

var parasha4616 =[
    "Parashá 46",
    "dia 16",
    "Shabbat Shalom á todos",
    "Hoje as 13:00 hrs ",
    "Reunião na congregação",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63

]



var data = new Date()
var dia = data.getDate()
var hora = data.getHours
var parasha = ""



 if (dia==17) {
    

    parasha=parasha4717 
 }
 if (dia==18) {
    if (hora<=12) {
      parasha=parasha4718m  
    }
    if (hora>=12) {
        parasha=parasha4718p 
    }
     
 }
if (dia==19) {
    

    parasha=parasha4719 
 }


export {parasha}



