    
var parasha4825m=[
    "Parashá 48",
    "dia 25 manhã",
    "Deuteronômio 16",
    "¹⁸ Juízes e oficiais porás em todas as tuas cidades que o Senhor teu Deus te der entre as tuas tribos, para que julguem o povo com juízo de justiça. ",
    "¹⁸ Juízes e oficiais porás em todas as tuas cidades que o Senhor teu Deus te der entre as tuas tribos, para que julguem o povo com juízo de justiça. ",
    "²⁰ A justiça, somente a justiça seguirás; para que vivas, e possuas em herança a terra que te dará o Senhor teu Deus. ",
    "²¹ Não plantarás nenhuma árvore junto ao altar do Senhor teu Deus, que fizeres para ti. ",
    "²² Nem levantarás imagem, a qual o Senhor teu Deus odeia. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63
] 
 
var parasha4825t=[
    "Parashá 48",
    "dia 25 tarde",
    "Deuteronômio 17",
    "¹ Não sacrificarás ao Senhor teu Deus, boi ou gado miúdo em que haja defeito ou alguma coisa má; pois abominação é ao Senhor teu Deus. ",
    "² Quando no meio de ti, em alguma das tuas portas que te dá o Senhor teu Deus, se achar algum homem ou mulher que fizer mal aos olhos do Senhor teu Deus, transgredindo a sua aliança, ",
    "³ Que se for, e servir a outros deuses, e se encurvar a eles ou ao sol, ou à lua, ou a todo o exército do céu, o que eu não ordenei, ",
    "⁴ E te for denunciado, e o ouvires; então bem o inquirirás; e eis que, sendo verdade, e certo que se fez tal abominação em Israel, ",
    "⁵ Então tirarás o homem ou a mulher que fez este malefício, às tuas portas, e apedrejarás o tal homem ou mulher, até que morra. ",
    "⁶ Por boca de duas testemunhas, ou três testemunhas, será morto o que houver de morrer; por boca de uma só testemunha não morrerá. ",
    "⁷ As mãos das testemunhas serão primeiro contra ele, para matá-lo; e depois as mãos de todo o povo; assim tirarás o mal do meio de ti. ",
    "⁸ Quando alguma coisa te for difícil demais em juízo, entre sangue e sangue, entre demanda e demanda, entre ferida e ferida, em questões de litígios nas tuas portas, então te levantarás, e subirás ao lugar que escolher o Senhor teu Deus; ",
    "⁹ E virás aos sacerdotes levitas, e ao juiz que houver naqueles dias, e inquirirás, e te anunciarão a sentença do juízo. ",
    "¹⁰ E farás conforme ao mandado da palavra que te anunciarem no lugar que escolher o Senhor; e terás cuidado de fazer conforme a tudo o que te ensinarem. ",
    "¹¹ Conforme ao mandado da lei que te ensinarem, e conforme ao juízo que te disserem, farás; da palavra que te anunciarem te não desviarás, nem para a direita nem para a esquerda. ",
    "¹² O homem, pois, que se houver soberbamente, não dando ouvidos ao sacerdote, que está ali para servir ao Senhor teu Deus, nem ao juiz, esse homem morrerá; e tirarás o mal de Israel; ",
    "¹³ Para que todo o povo o ouça, e tema, e nunca mais se ensoberbeça. ",
    "¹⁴ Quando entrares na terra que te dá o Senhor teu Deus, e a possuíres, e nela habitares, e disseres: Porei sobre mim um rei, assim como têm todas as nações que estão em redor de mim; ",
    "¹⁵ Porás certamente sobre ti como rei aquele que escolher o Senhor teu Deus; dentre teus irmãos porás rei sobre ti; não poderás pôr homem estranho sobre ti, que não seja de teus irmãos. ",
    "¹⁶ Porém ele não multiplicará para si cavalos, nem fará voltar o povo ao Egito para multiplicar cavalos; pois o Senhor vos tem dito: Nunca mais voltareis por este caminho. ",
    "¹⁷ Tampouco para si multiplicará mulheres, para que o seu coração não se desvie; nem prata nem ouro multiplicará muito para si. ",
    "¹⁸ Será também que, quando se assentar sobre o trono do seu reino, então escreverá para si num livro, um traslado desta lei, do original que está diante dos sacerdotes levitas. ",
    "¹⁹ E o terá consigo, e nele lerá todos os dias da sua vida, para que aprenda a temer ao Senhor seu Deus, para guardar todas as palavras desta lei, e estes estatutos, para cumpri-los; ",
    "²⁰ Para que o seu coração não se levante sobre os seus irmãos, e não se aparte do mandamento, nem para a direita nem para a esquerda; para que prolongue os seus dias no seu reino, ele e seus filhos no meio de Israel. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63
]
var parasha4826m= [
    "Parashá 48",
    "dia 26  manhã",
    "Deuteronômio 18",
    "¹ Os sacerdotes levitas, toda a tribo de Levi, não terão parte nem herança com Israel; das ofertas queimadas do Senhor e da sua herança comerão. ",
    "² Por isso não terão herança no meio de seus irmãos; o Senhor é a sua herança, como lhes tem dito. ",
    "³ Este, pois, será o direito dos sacerdotes, a receber do povo, dos que oferecerem sacrifício, seja boi ou gado miúdo; que darão ao sacerdote a espádua e as queixadas e o bucho. ",
    "⁴ Dar-lhe-ás as primícias do teu grão, do teu mosto e do teu azeite, e as primícias da tosquia das tuas ovelhas. ",
    "⁵ Porque o Senhor teu Deus o escolheu de todas as tuas tribos, para que assista e sirva no nome do Senhor, ele e seus filhos, todos os dias. ",
    "⁶ E, quando chegar um levita de alguma das tuas portas, de todo o Israel, onde habitar; e vier com todo o desejo da sua alma ao lugar que o Senhor escolheu; ",
    "⁷ E servir no nome do Senhor seu Deus, como também todos os seus irmãos, os levitas, que assistem ali perante o Senhor, ",
    "⁸ Igual porção comerão, além das vendas do seu patrimônio. ",
    "⁹ Quando entrares na terra que o Senhor teu Deus te der, não aprenderás a fazer conforme as abominações daquelas nações. ",
    "¹⁰ Entre ti não se achará quem faça passar pelo fogo a seu filho ou a sua filha, nem adivinhador, nem prognosticador, nem agoureiro, nem feiticeiro; ",
    "¹¹ Nem encantador, nem quem consulte a um espírito adivinhador, nem mágico, nem quem consulte os mortos; ",
    "¹² Pois todo aquele que faz tal coisa é abominação ao Senhor; e por estas abominações o Senhor teu Deus os lança fora de diante de ti.",
    "¹³ Perfeito serás com o Senhor teu Deus. ",
    "¹⁴ Porque estas nações, que hás de possuir, ouvem os prognosticadores e os adivinhadores; porém a ti o Senhor teu Deus não permitiu tal coisa. ",
    "¹⁵ O Senhor teu Deus te levantará um profeta do meio de ti, de teus irmãos, como eu; a ele ouvireis; ",
    "¹⁶ Conforme a tudo o que pediste ao Senhor teu Deus em Horebe, no dia da assembleia, dizendo: Não ouvirei mais a voz do Senhor teu Deus, nem mais verei este grande fogo, para que não morra. ",
    "¹⁷ Então o Senhor me disse: Falaram bem naquilo que disseram. ",
    "¹⁸ Eis lhes suscitarei um profeta do meio de seus irmãos, como tu, e porei as minhas palavras na sua boca, e ele lhes falará tudo o que eu lhe ordenar. ",
    "¹⁹ E será que qualquer que não ouvir as minhas palavras, que ele falar em meu nome, eu o requererei dele. ",
    "²⁰ Porém o profeta que tiver a presunção de falar alguma palavra em meu nome, que eu não lhe tenha mandado falar, ou o que falar em nome de outros deuses, esse profeta morrerá. ",
    "²¹ E, se disseres no teu coração: Como conhecerei a palavra que o Senhor não falou? ",
    "²² Quando o profeta falar em nome do Senhor, e essa palavra não se cumprir, nem suceder assim; esta é palavra que o Senhor não falou; com soberba a falou aquele profeta; não tenhas temor dele. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63

] 
var parasha4826t=[
    "Parashá 48",
    "dia 26 Tarde",
    "Deuteronômio 19",
    "¹ Quando o Senhor teu Deus desarraigar as nações cuja terra te dará o Senhor teu Deus, e tu as possuíres, e morares nas suas cidades e nas suas casas, ",
    "² Três cidades separarás, no meio da terra que te dará o Senhor teu Deus para a possuíres. ",
    "³ Preparar-te-ás o caminho; e os termos da tua terra, que te fará possuir o Senhor teu Deus, dividirás em três; e isto será para que todo o homicida se acolha ali. ",
    "⁴ E este é o caso tocante ao homicida, que se acolher ali, para que viva; aquele que por engano ferir o seu próximo, a quem não odiava antes; ",
    "⁵ Como aquele que entrar com o seu próximo no bosque, para cortar lenha, e, pondo força na sua mão com o machado para cortar a árvore, o ferro saltar do cabo e ferir o seu próximo e este morrer, aquele se acolherá a uma destas cidades, e viverá; ",
    "⁶ Para que o vingador do sangue não vá após o homicida, quando se enfurecer o seu coração, e o alcançar, por ser comprido o caminho, e lhe tire a vida; porque não é culpado de morte, pois o não odiava antes. ",
    "⁷ Portanto te dou ordem, dizendo: Três cidades separarás. ",
    "⁸ E, se o Senhor teu Deus dilatar os teus termos, como jurou a teus pais, e te der toda a terra que disse daria a teus pais ",
    "⁹ (Quando guardares todos estes mandamentos, que hoje te ordeno, para cumpri-los, amando ao Senhor teu Deus e andando nos seus caminhos todos os dias), então acrescentarás outras três cidades além destas três. ",
    "¹⁰ Para que o sangue inocente não se derrame no meio da tua terra, que o Senhor teu Deus te dá por herança, e haja sangue sobre ti. ",
    "¹¹ Mas, havendo alguém que odeia a seu próximo, e lhe arma ciladas, e se levanta contra ele, e o fere mortalmente, de modo que morra, e acolhe a alguma destas cidades, ",
    "¹² Então os anciãos da sua cidade mandarão buscá-lo; e dali o tirarão, e o entregarão na mão do vingador do sangue, para que morra. ",
    "¹³ O teu olho não o perdoará; antes tirarás o sangue inocente de Israel, para que bem te suceda. ",
    "¹⁴ Não mudes o limite do teu próximo, que estabeleceram os antigos na tua herança, que receberás na terra que te dá o Senhor teu Deus para a possuíres. ",
    "¹⁵ Uma só testemunha contra alguém não se levantará por qualquer iniquidade, ou por qualquer pecado, seja qual for o pecado que cometeu; pela boca de duas testemunhas, ou pela boca de três testemunhas, se estabelecerá o fato. ",
    "¹⁶ Quando se levantar testemunha falsa contra alguém, para testificar contra ele acerca de transgressão, ",
    "¹⁷ Então aqueles dois homens, que tiverem a demanda, se apresentarão perante o Senhor, diante dos sacerdotes e dos juízes que houver naqueles dias. ",
    "¹⁸ E os juízes inquirirão bem; e eis que, sendo a testemunha falsa, que testificou falsamente contra seu irmão, ",
    "¹⁹ Far-lhe-eis como cuidou fazer a seu irmão; e assim tirarás o mal do meio de ti. ",
    "²⁰ Para que os que ficarem o ouçam e temam, e nunca mais tornem a fazer tal mal no meio de ti. ",
    "²¹ O teu olho não perdoará; vida por vida, olho por olho, dente por dente, mão por mão, pé por pé. ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63

]
var parasha4827m =[
  "Parashá 48",
  "dia 27 mnhã",
  "Deuteronômio 20",
  "¹ Quando saíres à peleja contra teus inimigos, e vires cavalos, e carros, e povo maior em número do que tu, deles não terás temor; pois o Senhor teu Deus, que te tirou da terra do Egito, está contigo. ",
  "¹ Quando saíres à peleja contra teus inimigos, e vires cavalos, e carros, e povo maior em número do que tu, deles não terás temor; pois o Senhor teu Deus, que te tirou da terra do Egito, está contigo. ",
  "³ E dir-lhe-á: Ouvi, ó Israel, hoje vos achegais à peleja contra os vossos inimigos; não se amoleça o vosso coração: não temais nem tremais, nem vos aterrorizeis diante deles, ",
  "⁴ Pois o Senhor vosso Deus é o que vai convosco, a pelejar contra os vossos inimigos, para salvar-vos. ",
  "⁵ Então os oficiais falarão ao povo, dizendo: Qual é o homem que edificou casa nova e ainda não a consagrou? Vá, e torne-se à sua casa para que porventura não morra na peleja e algum outro a consagre. ",
  "⁶ E qual é o homem que plantou uma vinha e ainda não a desfrutou? Vá, e torne-se à sua casa, para que porventura não morra na peleja e algum outro a desfrute. ",
  "⁷ E qual é o homem que está desposado com alguma mulher e ainda não a recebeu? Vá, e torne-se à sua casa, para que porventura não morra na peleja e algum outro homem a receba. ",
  "⁸ E continuarão os oficiais a falar ao povo, dizendo: Qual é o homem medroso e de coração tímido? Vá, e torne-se à sua casa, para que o coração de seus irmãos não se derreta como o seu coração. ",
  "⁹ E será que, quando os oficiais acabarem de falar ao povo, então designarão os capitães dos exércitos para a dianteira do povo. ",
  "⁹ E será que, quando os oficiais acabarem de falar ao povo, então designarão os capitães dos exércitos para a dianteira do povo. ",
  "¹¹ E será que, se te responder em paz, e te abrir as portas, todo o povo que se achar nela te será tributário e te servirá. ",
  "¹² Porém, se ela não fizer paz contigo, mas antes te fizer guerra, então a sitiarás. ",
  "¹³ E o Senhor teu Deus a dará na tua mão; e todo o homem que houver nela passarás ao fio da espada. ",
  "¹⁴ Porém, as mulheres, e as crianças, e os animais; e tudo o que houver na cidade, todo o seu despojo, tomarás para ti; e comerás o despojo dos teus inimigos, que te deu o Senhor teu Deus. ",
  "¹⁵ Assim farás a todas as cidades que estiverem mui longe de ti, que não forem das cidades destas nações. ",
  "¹⁶ Porém, das cidades destas nações, que o Senhor teu Deus te dá em herança, nenhuma coisa que tem fôlego deixarás com vida. ",
  "¹⁷ Antes destruí-las-ás totalmente: aos heteus, e aos amorreus, e aos cananeus, e aos perizeus, e aos heveus, e aos jebuseus, como te ordenou o Senhor teu Deus. ",
  "¹⁸ Para que não vos ensinem a fazer conforme a todas as suas abominações, que fizeram a seus deuses, e pequeis contra o Senhor vosso Deus. ",
  "¹⁹ Quando sitiares uma cidade por muitos dias, pelejando contra ela para a tomar, não destruirás o seu arvoredo, colocando nele o machado, porque dele comerás; pois que não o cortarás (pois o arvoredo do campo é mantimento para o homem), para empregar no cerco. ",
  "²⁰ Mas as árvores que souberes que não são árvores de alimento, destruí-las-ás e cortá-las-ás; e contra a cidade que guerrear contra ti edificarás baluartes, até que esta seja vencida. ",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",//63

]
var parasha4827t =[
  "Parashá 48",
  "dia 27 Tarde",
  "Deuteronômio 21 v1 ao 10",
  "¹ Quando na terra que te der o Senhor teu Deus, para possuí-la, se achar um morto, caído no campo, sem que se saiba quem o matou, ",
  "² Então sairão os teus anciãos e os teus juízes, e medirão a distância até as cidades que estiverem em redor do morto; ",
  "³ E, na cidade mais próxima ao morto, os anciãos da mesma cidade tomarão uma novilha da manada, que não tenha trabalhado nem tenha puxado com o jugo; ",
  "⁴ E os anciãos daquela cidade trarão a novilha a um vale áspero, que nunca foi lavrado nem semeado; e ali, naquele vale, degolarão a novilha; ",
  "⁵ Então se achegarão os sacerdotes, filhos de Levi; pois o Senhor teu Deus os escolheu para o servirem, e para abençoarem em nome do Senhor; e pela sua palavra se decidirá toda a demanda e todo o ferimento; ",
  "⁶ E todos os anciãos da mesma cidade, mais próxima ao morto, lavarão as suas mãos sobre a novilha degolada no vale; ",
  "⁷ E protestarão, e dirão: As nossas mãos não derramaram este sangue, e os nossos olhos o não viram. ",
  "⁸ Sê propício ao teu povo Israel, que tu, ó Senhor, resgataste, e não ponhas o sangue inocente no meio do teu povo Israel. E aquele sangue lhes será expiado. ",
  "⁹ Assim tirarás o sangue inocente do meio de ti; pois farás o que é reto aos olhos do Senhor. ",
  "¹⁰ Quando saíres à peleja contra os teus inimigos, e o Senhor teu Deus os entregar nas tuas mãos, e tu deles levares prisioneiros, ",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",//63

]   




var parasha4723 =[
    "Parashá 47",
    "dia 23",
    "Shabbat Shalom á todos",
    "Hoje as 13:00 hrs ",
    "Reunião na congregação",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",//63

]




var data = new Date()
var dia = data.getDate()
var hor = data.getHours()
var parasha = ""



 if (dia=25) {
    if (hor<=12) {
      parasha=parasha4825m
    }
    if (hor>=12) {
        parasha=parasha4825t   
       }
 }
 
 if (dia=26) {
    if (hor>11) {
      parasha=parasha4826m   
    } else {
      parasha=parasha4826t 
    }
     
 }
 if (dia=27) {
  if (hor>11) {
    parasha=parasha4827m   
  } else {
    parasha=parasha4827t 
  }
   
} 
    
   
    

     
 






export {parasha}




